//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace PartialViewAspNet.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MobiBookEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MobiBookEntities object using the connection string found in the 'MobiBookEntities' section of the application configuration file.
        /// </summary>
        public MobiBookEntities() : base("name=MobiBookEntities", "MobiBookEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MobiBookEntities object.
        /// </summary>
        public MobiBookEntities(string connectionString) : base(connectionString, "MobiBookEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MobiBookEntities object.
        /// </summary>
        public MobiBookEntities(EntityConnection connection) : base(connection, "MobiBookEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MobiBookModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="pK_SearchId">Initial value of the PK_SearchId property.</param>
        /// <param name="allYouCanRead">Initial value of the AllYouCanRead property.</param>
        public static Product CreateProduct(global::System.Int64 pK_SearchId, global::System.Boolean allYouCanRead)
        {
            Product product = new Product();
            product.PK_SearchId = pK_SearchId;
            product.AllYouCanRead = allYouCanRead;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PK_SearchId
        {
            get
            {
                return _PK_SearchId;
            }
            set
            {
                if (_PK_SearchId != value)
                {
                    OnPK_SearchIdChanging(value);
                    ReportPropertyChanging("PK_SearchId");
                    _PK_SearchId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PK_SearchId");
                    OnPK_SearchIdChanged();
                }
            }
        }
        private global::System.Int64 _PK_SearchId;
        partial void OnPK_SearchIdChanging(global::System.Int64 value);
        partial void OnPK_SearchIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PK_ProductID
        {
            get
            {
                return _PK_ProductID;
            }
            set
            {
                OnPK_ProductIDChanging(value);
                ReportPropertyChanging("PK_ProductID");
                _PK_ProductID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PK_ProductID");
                OnPK_ProductIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PK_ProductID;
        partial void OnPK_ProductIDChanging(Nullable<global::System.Int32> value);
        partial void OnPK_ProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductCode
        {
            get
            {
                return _ProductCode;
            }
            set
            {
                OnProductCodeChanging(value);
                ReportPropertyChanging("ProductCode");
                _ProductCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductCode");
                OnProductCodeChanged();
            }
        }
        private global::System.String _ProductCode;
        partial void OnProductCodeChanging(global::System.String value);
        partial void OnProductCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author;
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Point
        {
            get
            {
                return _Point;
            }
            set
            {
                OnPointChanging(value);
                ReportPropertyChanging("Point");
                _Point = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Point");
                OnPointChanged();
            }
        }
        private Nullable<global::System.Int32> _Point;
        partial void OnPointChanging(Nullable<global::System.Int32> value);
        partial void OnPointChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PublishDate
        {
            get
            {
                return _PublishDate;
            }
            set
            {
                OnPublishDateChanging(value);
                ReportPropertyChanging("PublishDate");
                _PublishDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PublishDate");
                OnPublishDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PublishDate;
        partial void OnPublishDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPublishDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> MappedDate
        {
            get
            {
                return _MappedDate;
            }
            set
            {
                OnMappedDateChanging(value);
                ReportPropertyChanging("MappedDate");
                _MappedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MappedDate");
                OnMappedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _MappedDate;
        partial void OnMappedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnMappedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AllYouCanRead
        {
            get
            {
                return _AllYouCanRead;
            }
            set
            {
                OnAllYouCanReadChanging(value);
                ReportPropertyChanging("AllYouCanRead");
                _AllYouCanRead = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllYouCanRead");
                OnAllYouCanReadChanged();
            }
        }
        private global::System.Boolean _AllYouCanRead;
        partial void OnAllYouCanReadChanging(global::System.Boolean value);
        partial void OnAllYouCanReadChanged();

        #endregion
    
    }

    #endregion
    
}
